CREATE TABLE IF NOT EXISTS admin_roles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL UNIQUE,description TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_role_bindings(account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,role_id UUID NOT NULL REFERENCES admin_roles(id) ON DELETE CASCADE,granted_by UUID REFERENCES accounts(id),granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),revoked_at TIMESTAMPTZ,PRIMARY KEY(account_id,role_id));
CREATE TABLE IF NOT EXISTS admin_permissions(code TEXT PRIMARY KEY,description TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_role_permissions(role_id UUID NOT NULL REFERENCES admin_roles(id) ON DELETE CASCADE,permission_code TEXT NOT NULL REFERENCES admin_permissions(code),PRIMARY KEY(role_id,permission_code));
CREATE TABLE IF NOT EXISTS admin_audit_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),actor_account_id UUID REFERENCES accounts(id),action_code TEXT NOT NULL,resource_type TEXT NOT NULL,resource_id UUID,decision TEXT NOT NULL CHECK(decision IN('allowed','denied')),reason TEXT,request_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),previous_hash TEXT,current_hash TEXT);
CREATE INDEX IF NOT EXISTS admin_audit_resource_idx ON admin_audit_events(resource_type,resource_id,created_at DESC);
INSERT INTO admin_roles(name,description) VALUES('super_admin','full administrative scope'),('operations_admin','marketplace operations'),('finance_admin','financial operations'),('moderation_admin','moderation and abuse'),('read_only_auditor','read only') ON CONFLICT(name) DO NOTHING;
INSERT INTO admin_permissions(code,description) VALUES
('users.read','read users'),('users.manage','manage users'),('sellers.read','read sellers'),('sellers.manage','manage sellers'),('listings.read','read listings'),('listings.manage','moderate listings'),
('orders.read','read orders'),('orders.manage','manage orders'),('payments.read','read payments'),('escrow.read','read escrow'),('escrow.manage','guarded escrow'),
('wallets.read','read custody metadata'),('withdrawals.read','read withdrawals'),('withdrawals.approve','approve withdrawals'),('payouts.read','read payouts'),('payouts.approve','approve payouts'),
('points.read','read points'),('points.manage','manage points'),('promos.manage','manage promos'),('settings.read','read settings'),('settings.manage','manage settings'),
('audit.read','read audit'),('emergency.manage','emergency controls') ON CONFLICT(code) DO NOTHING;
INSERT INTO admin_role_permissions(role_id,permission_code) SELECT r.id,p.code FROM admin_roles r JOIN admin_permissions p ON p.code IN('users.read','users.manage','sellers.read','sellers.manage','listings.read','listings.manage','orders.read','orders.manage','points.read','points.manage','promos.manage','audit.read') WHERE r.name='operations_admin' ON CONFLICT DO NOTHING;
INSERT INTO admin_role_permissions(role_id,permission_code) SELECT r.id,p.code FROM admin_roles r JOIN admin_permissions p ON p.code IN('sellers.read','payments.read','escrow.read','escrow.manage','wallets.read','withdrawals.read','withdrawals.approve','payouts.read','payouts.approve','audit.read','emergency.manage') WHERE r.name='finance_admin' ON CONFLICT DO NOTHING;
INSERT INTO admin_role_permissions(role_id,permission_code) SELECT r.id,p.code FROM admin_roles r JOIN admin_permissions p ON p.code IN('users.read','sellers.read','sellers.manage','listings.read','listings.manage','orders.read','audit.read') WHERE r.name='moderation_admin' ON CONFLICT DO NOTHING;
INSERT INTO admin_role_permissions(role_id,permission_code) SELECT r.id,p.code FROM admin_roles r JOIN admin_permissions p ON p.code IN('users.read','sellers.read','listings.read','orders.read','payments.read','escrow.read','wallets.read','withdrawals.read','payouts.read','points.read','audit.read','settings.read') WHERE r.name='read_only_auditor' ON CONFLICT DO NOTHING;
INSERT INTO admin_role_permissions(role_id,permission_code) SELECT r.id,p.code FROM admin_roles r CROSS JOIN admin_permissions p WHERE r.name='super_admin' ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS seller_point_levels(level SMALLINT PRIMARY KEY,name TEXT NOT NULL UNIQUE,min_points BIGINT NOT NULL CHECK(min_points>=0),min_completed_sales INTEGER NOT NULL DEFAULT 0 CHECK(min_completed_sales>=0),max_dispute_rate_bps INTEGER NOT NULL DEFAULT 10000 CHECK(max_dispute_rate_bps BETWEEN 0 AND 10000),advance_payout_allowed BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE);
INSERT INTO seller_point_levels(level,name,min_points,min_completed_sales,max_dispute_rate_bps,advance_payout_allowed) VALUES(0,'Nuevo',0,0,10000,FALSE),(1,'Establecido',100,5,2500,FALSE),(2,'Confiable',500,20,1000,FALSE),(3,'Avanzado',1500,50,500,TRUE),(4,'Preferente',3000,100,250,TRUE) ON CONFLICT(level) DO NOTHING;
CREATE TABLE IF NOT EXISTS seller_points_ledger(id BIGSERIAL PRIMARY KEY,seller_account_id UUID NOT NULL REFERENCES sellers(account_id),delta_points INTEGER NOT NULL CHECK(delta_points<>0),reason_code TEXT NOT NULL,reference_id UUID,idempotency_key TEXT NOT NULL UNIQUE,actor UUID REFERENCES accounts(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE OR REPLACE VIEW seller_point_balances AS SELECT seller_account_id,COALESCE(SUM(delta_points),0)::BIGINT points FROM seller_points_ledger GROUP BY seller_account_id;
CREATE TABLE IF NOT EXISTS seller_payout_policies(mode TEXT PRIMARY KEY,label TEXT NOT NULL,requires_level SMALLINT NOT NULL REFERENCES seller_point_levels(level),buyer_protection_required BOOLEAN NOT NULL,admin_approval_required BOOLEAN NOT NULL DEFAULT TRUE,active BOOLEAN NOT NULL DEFAULT TRUE);
INSERT INTO seller_payout_policies(mode,label,requires_level,buyer_protection_required,admin_approval_required) VALUES('standard_escrow','Liquidación protegida',0,TRUE,FALSE),('early_release','Liquidación anticipada limitada',3,TRUE,TRUE),('advance_payout','Pago anticipado',4,FALSE,TRUE) ON CONFLICT(mode) DO NOTHING;
CREATE TABLE IF NOT EXISTS seller_payout_mode_requests(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),seller_account_id UUID NOT NULL REFERENCES sellers(account_id),requested_mode TEXT NOT NULL REFERENCES seller_payout_policies(mode),seller_points_snapshot BIGINT NOT NULL CHECK(seller_points_snapshot>=0),completed_sales_snapshot INTEGER NOT NULL CHECK(completed_sales_snapshot>=0),dispute_rate_bps_snapshot INTEGER NOT NULL CHECK(dispute_rate_bps_snapshot BETWEEN 0 AND 10000),status TEXT NOT NULL DEFAULT 'requested' CHECK(status IN('requested','approved','rejected','suspended','revoked')),reviewed_by UUID REFERENCES accounts(id),review_reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),reviewed_at TIMESTAMPTZ);
